# Generated by Django 5.2.3 on 2025-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land'), ('INDUSTRIAL', 'Industrial'), ('RETAIL', 'Retail')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('land_size_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
